### ISSUE TITLE
Torrent911

### ISSUE THREAD

**Issue by biglat1595** [Prowlarr/Indexers#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Wrong url : https://oxtorrent.zip

### Expected Behavior

change to new url https://torrent911.tw

### Environment

```markdown
- OS:
- Prowlarr: 1.18.0.4543
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

No logs

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/fc3e7c674bb0887cda4f97e7f828bc42cf486596

**Comment by bakerboy448** [comment]
correct new url is oxtorrent vip

**Comment by biglat1595** [comment]
Hi, those are 2 differents trackers.
new url for oxtorrent is oxtorrent.vip and for torrent911 is torrent911.tw

**Comment by garfield69** [comment]
torrent911 indexer uses the oxtorrent.vip domain because that site still uses the torrent list view, where as the original torrent911.tw switched to a poster view that is less suitable for indexing.
not to be confused with oxtorrent.co which is a different site again and uses different search paths.
